# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1837cc1e022882f93fc72a94cbba30617364ef2a6f67bd600247b746c5a01e7aa5f6ed4d76b6830774889bc4d107ff640c32df1039d24b2d4f810d87ad2b2eee

test:
  secret_key_base: 0b67c3819441f9949d8657f1b9fc6b85d50db6b545046077dd9d84485184446507ffaf787637f40680414f047578cdd53415f2fb74481fe8cc30c7d4cbaf1945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
